## *colab*.research.google.*com*

In [10]:
import os

In [5]:
from google.colab import drive
drive.mount ('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [6]:
from nltk.tokenize import word_tokenize

In [2]:
import pandas as pd

In [8]:
!pip install --upgrade numpy

  Using cached numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Using cached numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.5 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.5 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.5 which is incompatible.


In [9]:
!pip install --upgrade numpy
!pip install --force-reinstall gensim

  Using cached gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
  Using cached scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
  Using cached smart_open-7.1.0-py3-none-any.whl.metadata (24 kB)
  Using cached wrapt-1.17.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Using cached gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Using cached scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
Using cached smart_open-7.1.0-py3-none-any.whl (61 kB)
Using cached wrapt-1.17.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (83 kB)
  Att

In [3]:
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec
from tqdm.auto import tqdm
df=pd.read_csv ("/content/drive/MyDrive/DATASET-TEXT/tokopedia_reviews_dirty.csv")
df.head(5)

Unnamed: 0                                             text  rating  \
0           1           Barang sesuai pesanan dan cepat sampai       5   
1           2                         Barang bagus harga murah       5   
2           3  Paket rapi...mantap....cepat....sampe ke tujuan       5   
3           4                       ya saya puas dgn barangnya       5   
4           5                     Responya luar biasa b mantap       5   

      category                                       product_name  product_id  \
0  pertukangan  Staples Dekorasi Staples Kayu + Refill 8mm - S...   418660637   
1  pertukangan  STAPLE GUN ATS 3 WAY TACKER - STAPLES JOK TEMB...   416032545   
2  pertukangan  STAPLE GUN ATS 3 WAY TACKER - STAPLES JOK TEMB...   416032545   
3  pertukangan  ALAT STAPLES TEMBAK &#40;AIR NAILER GUN&#41; O...   102279869   
4  pertukangan  Isi Refill Staples Jok Kulit Motor / Staple Gu...   190679689   

  sold  shop_id                                        product_url  
0    1  1740837  https://www.tokopedia.com/shakaonline87/staple...  
1   11  1477109  https://www.tokopedia.com/juraganperkakas/stap...  
2   11  1477109  https://www.tokopedia.com/juraganperkakas/stap...  
3    5   771395  https://www.tokopedia.com/kamarmesin/alat-stap...  
4  787   969999  https://www.tokopedia.com/mitrapersada/isi-ref...

In [6]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [7]:
sentences = [word_tokenize(review.lower()) for review in tqdm(df.text)]
sentences [:10]

  0%|          | 0/40607 [00:00<?, ?it/s]

[['barang', 'sesuai', 'pesanan', 'dan', 'cepat', 'sampai'],
 ['barang', 'bagus', 'harga', 'murah'],
 ['paket',
  'rapi',
  '...',
  'mantap',
  '....',
  'cepat',
  '....',
  'sampe',
  'ke',
  'tujuan'],
 ['ya', 'saya', 'puas', 'dgn', 'barangnya'],
 ['responya', 'luar', 'biasa', 'b', 'mantap'],
 ['seller', 'top', ',', 'pengiriman', 'cepat', 'barang', 'oke'],
 ['pengiriman', 'cepat', 'seller', 'top'],
 ['produk',
  'sesuai',
  'dengan',
  'spec',
  'di',
  'web',
  'dan',
  'respon',
  'seller',
  'sangat',
  'cepat',
  '.',
  'thankyou',
  '.'],
 ['respon',
  'super',
  'cepat',
  ',',
  'pengiriman',
  'cepat',
  ',',
  'barang',
  'bagus',
  'sesuai',
  'deskripsi',
  'penjual',
  '..',
  'thx',
  'gan'],
 ['barang', 'mantap', ',', 'pelayanan', 'cepat']]

In [8]:
model = Word2Vec (sentences, vector_size=128, window=5, min_count=3, epochs=100, sg=0, hs=0)

MENYIMPAN MODEL

In [11]:
os.makedirs ("/content/model/w2v/", exist_ok=True)

In [12]:
model.save ("/content/product_reviews_dirty.w2v")

LOAD MODEL

In [13]:
model=Word2Vec.load("/content/product_reviews_dirty.w2v")

TRAINING

In [14]:
" layanannya bagus untuk kebutuhan sehari-hari dan kerja".lower() .split()

['layanannya', 'bagus', 'untuk', 'kebutuhan', 'sehari-hari', 'dan', 'kerja']

In [15]:
contoh_data=[
    ['aplikasinya','enak','digunakan','dan','harganya','murah','dan','kompetirif'],
    ['driver','ramah-ramah','komunikatif','murah','senyum','dan','pro-aktif']
]

PRE-TRAIN

In [16]:
model.train (contoh_data, total_examples=len (contoh_data), epochs=1)

(9, 15)

In [17]:
w2v=model.wv

In [18]:
w2v.index_to_key

[',',
 '.',
 'barang',
 'sesuai',
 'cepat',
 'dan',
 'bagus',
 '..',
 '...',
 'dengan',
 'sudah',
 'sampai',
 'pengiriman',
 'baik',
 'terima',
 'respon',
 'gan',
 'di',
 'kasih',
 '!',
 'produk',
 'pesanan',
 'seller',
 'mantap',
 'diterima',
 'deskripsi',
 'nya',
 'packing',
 'yg',
 'thanks',
 'ok',
 'saya',
 'barangnya',
 'kualitas',
 '....',
 'sangat',
 'oke',
 'fast',
 'harga',
 'berfungsi',
 'rapi',
 'terimakasih',
 'semoga',
 'gambar',
 'yang',
 'ada',
 'awet',
 'ya',
 'tapi',
 'recommended',
 'good',
 'makasih',
 'juga',
 'dgn',
 'banget',
 'tidak',
 'sdh',
 'ini',
 '&',
 ')',
 'bisa',
 ';',
 ':',
 'sukses',
 'udah',
 'sampe',
 'untuk',
 'tp',
 'cepet',
 'thx',
 'aman',
 'rapih',
 'penjual',
 'puas',
 'pelayanan',
 'ga',
 'lah',
 'lumayan',
 'murah',
 'recomended',
 'paket',
 'buat',
 'dah',
 'selamat',
 '.....',
 'agak',
 'lama',
 'dicoba',
 'warna',
 'brg',
 'pas',
 'belum',
 'order',
 'top',
 'baru',
 'bintang',
 'lagi',
 'bgt',
 'beli',
 'jam',
 'gak',
 'sama',
 'selalu',
 

In [19]:
w2v.vectors

array([[-0.172395  ,  0.19769412, -0.83589804, ..., -0.48303354,
        -0.21247466,  0.02706967],
       [ 0.6967543 ,  0.47901368,  0.0114462 , ...,  1.4698611 ,
        -0.37114856,  0.96869695],
       [-0.10054422, -0.3835014 , -0.44483113, ...,  1.0517894 ,
         0.06072383,  0.76351553],
       ...,
       [-0.11806223, -0.16376081,  0.13147676, ...,  0.10439102,
        -0.12364756,  0.23592298],
       [-0.56483585, -0.2539016 ,  0.09912173, ..., -0.672048  ,
         0.03124529,  0.32339403],
       [-0.16284658,  0.12328496,  0.07918011, ...,  0.66358507,
        -0.29397678, -0.68486035]], dtype=float32)

In [20]:
w2v.vector_size

128

VECKTOR PER KATA

In [21]:
w2v["harga"]

array([ 1.4296457 , -2.7810035 , -0.99191266, -1.3671334 , -0.52231044,
        0.04430708, -0.98148936,  0.20867808,  1.7609922 , -0.19818993,
        0.08846895,  4.423341  ,  0.12511905, -1.7140206 , -4.1655273 ,
       -0.8602524 ,  2.8714418 , -1.7506015 , -0.29486698,  1.535076  ,
       -1.5338994 , -2.0316825 ,  0.5635867 , -1.109864  , -0.4830296 ,
        0.16573319, -1.4204723 ,  0.892859  , -0.05535123,  1.4935962 ,
       -0.574874  ,  1.3757348 , -1.1982491 , -0.00872442,  0.7807085 ,
       -1.9243864 , -0.316476  ,  0.53211343, -2.2852812 ,  0.1543649 ,
       -1.3564793 ,  0.2682585 , -0.4072497 ,  1.1708376 ,  2.596057  ,
        0.80968326, -0.22293766, -0.20832522, -0.8650748 ,  2.1099584 ,
        1.8880241 , -0.8923959 , -0.402513  , -1.0450833 ,  0.15681128,
        0.14469299, -1.6561916 , -0.2506846 ,  2.1544373 , -0.19056588,
       -0.19011852, -0.07322636, -0.28253832, -0.2817575 , -0.4257565 ,
        0.35543072, -2.95311   ,  2.0932918 ,  0.6016354 , -0.49

In [23]:
w2v["biaya"]

array([-2.6275141 , -0.9342058 ,  0.16469724, -1.5198203 , -0.93644726,
        0.15077142,  0.08197161, -0.27317196,  0.873859  ,  0.49908033,
       -0.8355641 ,  1.1477215 , -0.11113933,  1.0871589 , -0.16988534,
       -0.86654025,  0.4837448 , -0.4616465 , -0.37328798, -1.1845487 ,
       -0.29990274,  1.3570172 , -0.5943802 , -0.28446004,  2.4686124 ,
        0.99649316, -0.3383963 ,  0.58299845,  2.178179  , -0.00449135,
       -1.3896976 , -0.30486178, -1.2629646 , -1.104241  , -0.16709523,
       -2.1949513 ,  0.02021256,  2.0693653 , -1.0725199 , -0.42315915,
        1.6187162 ,  0.6920288 ,  1.4968419 ,  0.2852312 ,  0.23309372,
        1.414162  , -2.5558662 , -1.6095816 ,  1.0881735 ,  0.82075965,
        0.7573073 ,  0.01846537,  0.87265646, -1.4903804 , -1.1603247 ,
        0.7226362 ,  0.6856043 ,  1.0501322 , -0.42750925,  1.0996321 ,
       -0.18737115, -0.81984454,  1.2266734 , -0.3562715 ,  0.45606926,
        0.07840545, -1.0865325 ,  0.37679464, -0.52858484,  0.27

In [24]:
w2v["pas"]

array([-3.1572218 ,  2.2557735 , -0.06124057, -0.47053224, -1.1381221 ,
        1.2811003 ,  0.6714513 , -0.15603103, -1.766455  , -1.29838   ,
       -0.02879571, -0.5209813 ,  0.26657814, -0.8553774 ,  2.5402534 ,
       -1.5169333 , -1.6892892 , -0.51328725, -1.2945031 ,  0.3619137 ,
        0.51814574,  0.57524186, -3.0392952 , -0.46254668, -0.5472973 ,
        3.210116  ,  0.5519368 ,  3.7903306 , -2.750042  ,  1.3449522 ,
       -0.25201976,  0.36939222, -1.8126072 ,  0.46872228,  0.913597  ,
       -0.68493223,  0.9008521 , -0.08006816,  3.190185  ,  0.14942577,
        0.3053248 , -2.4313412 , -0.78298193,  2.3320491 , -2.0584056 ,
        0.95452994,  3.1004207 , -0.4558022 , -1.5359907 ,  1.704065  ,
       -0.18288666,  2.647969  , -2.0318413 , -0.33026975, -0.02149066,
       -1.604563  ,  0.4782662 ,  2.8795075 ,  1.148993  , -1.1353848 ,
       -2.4117932 , -1.3589629 , -1.0647452 ,  3.3403368 , -2.0626621 ,
        0.76529735, -1.1831356 , -1.193523  , -2.4466503 ,  1.26

In [25]:
w2v["bisa"]

array([-2.096823  ,  0.03568812,  1.3139892 ,  2.6534271 ,  0.47556564,
       -0.8180301 ,  0.608507  ,  1.4091932 , -1.9441949 , -1.5822113 ,
       -1.573922  , -1.3477017 ,  1.6505154 , -1.4117687 , -0.04570596,
        0.07549248,  1.384701  , -1.787116  , -0.10497465,  1.366528  ,
        1.7458899 ,  1.0798197 , -0.5787623 , -1.6697203 ,  0.619741  ,
        0.04878365,  1.7066479 ,  1.4844751 ,  0.5852218 ,  0.52787685,
       -1.4168578 , -0.36140305, -1.1807525 , -1.2567426 ,  0.03084654,
        1.9703282 , -1.1785338 ,  1.7115884 , -0.09590009, -0.294281  ,
        0.12027472, -3.8325431 , -0.55071396,  0.87315285,  0.58957285,
        1.1560729 ,  0.18066001, -1.361817  ,  1.0962884 ,  0.5157813 ,
        1.7275963 ,  1.8078424 ,  0.9893405 ,  1.2743323 , -1.3987517 ,
        0.32972878,  2.5137196 ,  2.0459619 , -4.516021  , -1.2099643 ,
       -1.798569  , -1.9876765 ,  1.8157004 , -2.7920322 , -1.6299064 ,
       -2.5761375 , -1.2945663 , -1.0769346 , -1.2094284 ,  1.85

In [26]:
w2v["hanafi"]

KeyError: "Key 'hanafi' not present"

KEMIRIPAN KATA

In [27]:
w2v.similar_by_word ('cash',topn=20)

[('refund', 0.6221382021903992),
 ('kembalikan', 0.5356519818305969),
 ('uangnya', 0.5110406875610352),
 ('walopun', 0.4599687457084656),
 ('udara', 0.4441487789154053),
 ('gpp', 0.442717969417572),
 ('asuransi', 0.42473551630973816),
 ('dikasi', 0.42346465587615967),
 ('tulisannya', 0.41803810000419617),
 ('dikecewakan', 0.41529741883277893),
 ('kan', 0.40655282139778137),
 ('parkir', 0.4042932093143463),
 ('adanya', 0.4031044840812683),
 ('uang', 0.40249818563461304),
 ('syang', 0.40233176946640015),
 ('knapa', 0.3984043598175049),
 ('ketuker', 0.3945998251438141),
 ('ilang', 0.38973063230514526),
 ('gapapa', 0.3806445598602295),
 ('cd', 0.3791199326515198)]

In [28]:
w2v.similar_by_word ('harga',topn=20)

[('harganya', 0.689714789390564),
 ('hrga', 0.6052114367485046),
 ('hrg', 0.4188773036003113),
 ('deskripsi', 0.39348047971725464),
 ('relatif', 0.3886978328227997),
 ('kalah', 0.37185385823249817),
 ('harapan', 0.35979601740837097),
 ('difoto', 0.34546762704849243),
 ('gambar', 0.33980998396873474),
 ('maklum', 0.3278767466545105),
 ('ekspektasi', 0.3269372582435608),
 ('kettler', 0.3194361925125122),
 ('deakripsi', 0.3144548833370209),
 ('pic', 0.305987685918808),
 ('spesifikasi', 0.30588045716285706),
 ('meriah', 0.3040754497051239),
 ('lumayan', 0.3000469207763672),
 ('konektor', 0.2984740734100342),
 ('boleh', 0.2983722686767578),
 ('tergolong', 0.29537349939346313)]

In [29]:
w2v.similar_by_word ('mahal',topn=20)

[('segini', 0.48358139395713806),
 ('murah', 0.433418333530426),
 ('murahan', 0.4274977147579193),
 ('bentuk', 0.4248473346233368),
 ('segitu', 0.41366103291511536),
 ('kemahalan', 0.38946738839149475),
 ('miring', 0.38473090529441833),
 ('mewah', 0.3841598927974701),
 ('kalah', 0.3812641501426697),
 ('renang', 0.3794384300708771),
 ('rendah', 0.37159889936447144),
 ('pemain', 0.3675549030303955),
 ('sensitif', 0.3579752743244171),
 ('merek', 0.35703131556510925),
 ('apa2', 0.3533349633216858),
 ('kacau', 0.35268619656562805),
 ('worth', 0.35245051980018616),
 ('trnyata', 0.3517603278160095),
 ('semurah', 0.3511863946914673),
 ('pantas', 0.35108014941215515)]

In [30]:
w2v.similar_by_word ('murah',topn=10)

[('terjangkau', 0.5559855103492737),
 ('termurah', 0.5299659967422485),
 ('kompetitif', 0.5240967273712158),
 ('hemat', 0.49812009930610657),
 ('bersaing', 0.47063156962394714),
 ('segitu', 0.44108709692955017),
 ('bersahabat', 0.43574437499046326),
 ('mahal', 0.43341830372810364),
 ('miring', 0.40564772486686707),
 ('pantas', 0.4052984416484833)]

In [31]:
!pip install umap-learn

In [32]:
import umap.umap_ as umap
reducer = umap.UMAP()

In [33]:
import umap.umap_ as umap # Import the UMAP class from umap.umap_

# Now you can use UMAP as follows:
reducer = umap.UMAP()

In [34]:
import numpy as np
import pandas as pd
import plotly.express as px

In [35]:
import umap.umap_ as umap # Make sure umap-learn is installed

# Instantiate the UMAP object
reducer = umap.UMAP()

# Apply fit_transform to your data
X = reducer.fit_transform(w2v.vectors)
df = pd.DataFrame(X, columns=["umap1", "umap2"]) # Corrected column name

# Use index_to_key instead of index2word
df["text"] = w2v.index_to_key # Changed from index2word to index_to_key

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


In [36]:
df


umap1     umap2                    text
0     10.738803  4.354735                       ,
1     10.761600  4.335859                       .
2     10.716598  1.642808                  barang
3     10.021864  2.148166                  sesuai
4     10.818235  2.636215                   cepat
...         ...       ...                     ...
4878   7.521585  1.909566                shipment
4879  10.572060  2.047588               pesananan
4880  10.701952  3.061404  bagussssssssssssssssss
4881  11.397322  4.427261                     bca
4882  10.390688  5.795756                   diksh

[4883 rows x 3 columns]

In [37]:
from umap import UMAP # Import UMAP directly

X = UMAP().fit_transform(w2v.vectors)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


In [38]:
df = pd.DataFrame(X, columns=["umap1","umap2"])
df["text"] = w2v.index_to_key

In [39]:
df

umap1     umap2                    text
0     15.173097 -0.888670                       ,
1     15.140911 -0.978378                       .
2     13.697284 -2.833411                  barang
3     13.622509 -2.400501                  sesuai
4     13.405306 -1.885165                   cepat
...         ...       ...                     ...
4878  10.929198 -0.650550                shipment
4879  14.071735 -2.677221               pesananan
4880  14.225336 -1.867546  bagussssssssssssssssss
4881  13.258321  0.865076                     bca
4882  14.630749  0.331313                   diksh

[4883 rows x 3 columns]

In [40]:
fig = px.scatter(df, x="umap1", y="umap2", text="text")
fig.update_traces(textposition='top center')
fig.update_layout(height=2000, title_text='Reduce Word2Vec Visualisation')
fig.show()

HIGH ORDER VISUALISATION