<a href="https://colab.research.google.com/github/myhanafi/NLP-3/blob/main/word_vec_gojek.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os

In [ ]:
import pandas as pd

In [ ]:
!pip install gensim

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec
from tqdm.auto import tqdm
df=pd.read_csv ("/content/gojek_review.csv")
df.head()

review  rate
0  Sangat kecewa. Kecewa sekali. Udh top up. Mau ...     1
1  Ga niat ngasih promo sialan temen udh pake ref...     1
2  Kalau sistemnya rata begini apa bedanya yg raj...     1
3  Ongkosnya da mahal, minimal 16rb..... Sekarang...     1
4  Tolol anjing..!!!! Aplikasi yang katanga karya...     1

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
sentences = [word_tokenize(review.lower()) for review in tqdm(df.review)]
sentences [:5]

  0%|          | 0/1277 [00:00<?, ?it/s]

[['sangat',
  'kecewa',
  '.',
  'kecewa',
  'sekali',
  '.',
  'udh',
  'top',
  'up',
  '.',
  'mau',
  'di',
  'transaksi',
  'in',
  'malah',
  'kasih',
  'nomor',
  'yang',
  'salah',
  '.',
  'padahal',
  'nomor',
  'di',
  'profil',
  'benar',
  '.',
  'buat',
  'ap',
  'ah',
  'q',
  'top',
  'up',
  'tp',
  'ga',
  'bisa',
  'digunain',
  '.',
  'balikin.',
  '!',
  'ga',
  'becus',
  '.',
  'kasih',
  'nomer',
  'saalah',
  '.',
  'saya',
  'mau',
  'masukin',
  'kode',
  'transaksi',
  'gimana.',
  '!',
  '!',
  '!',
  '!'],
 ['ga',
  'niat',
  'ngasih',
  'promo',
  'sialan',
  'temen',
  'udh',
  'pake',
  'reff',
  'ga',
  'pake',
  'cara',
  'curang',
  'malah',
  'di',
  'stop',
  '.',
  'kapitalis',
  '.',
  'daerah',
  'ku',
  'ongkir',
  'ga',
  'ada',
  'subsidi',
  'di',
  'daerah',
  'lain',
  'masih',
  'ada',
  '.',
  'ampas',
  'gojek',
  'skrng',
  '.',
  'strategi',
  'baru',
  'ga',
  'bakar',
  'duit',
  'gimana',
  '.',
  'yg',
  'ada',
  'transaksi',
  'h

In [ ]:
model = Word2Vec (sentences, size=128, window=5, min_count=3, iter=1000, sg=0, hs=0)

MENYIMPAN MODEL

In [ ]:
os.makedirs ("/content/model/w2v/", exist_ok=True)

In [ ]:
model.save ("/content/model/w2v/gojek_review.w2v")

LOAD MODEL

In [ ]:
model=Word2Vec.load("model/w2v/gojek_review.w2v")

TRAINING

In [ ]:
" layanannya bagus untuk kebutuhan sehari-hari dan kerja".lower() .split()

['layanannya', 'bagus', 'untuk', 'kebutuhan', 'sehari-hari', 'dan', 'kerja']

In [ ]:
contoh_data=[
    ['aplikasinya','enak','digunakan','dan','harganya','murah','dan','kompetirif'],
    ['driver','ramah-ramah','komunikatif','murah','senyum','dan','pro-aktif']
]

PRE-TRAIN

In [ ]:
model.train (contoh_data, total_examples=len (contoh_data), epochs=1)

(7, 15)

In [ ]:
w2v=model.wv

In [ ]:
w2v.index2word

[',',
 '.',
 'saya',
 '!',
 'di',
 'gojek',
 '..',
 'yg',
 'bisa',
 '?',
 'ada',
 'nya',
 'driver',
 'dan',
 'ini',
 'aplikasi',
 'tidak',
 'yang',
 'gak',
 'mau',
 'ga',
 'lagi',
 '...',
 'tolong',
 'aja',
 'sudah',
 'tapi',
 'untuk',
 'voucher',
 'padahal',
 'gopay',
 'ke',
 'sama',
 'udah',
 'order',
 'lebih',
 'sangat',
 'akun',
 'dengan',
 'ya',
 'buat',
 'sekarang',
 'kenapa',
 'jadi',
 'kasih',
 'malah',
 'lama',
 'dari',
 'gofood',
 'itu',
 'promo',
 'kalo',
 'jauh',
 'juga',
 'dapat',
 'pake',
 'karena',
 'masuk',
 'banyak',
 'terus',
 'kalau',
 'apa',
 'baru',
 'dong',
 'go',
 'kok',
 'gk',
 'kecewa',
 'pakai',
 'harus',
 'selalu',
 'orderan',
 'pesan',
 'sistem',
 'hari',
 'cuma',
 'makin',
 'tp',
 "''",
 'saldo',
 'banget',
 'dulu',
 'atau',
 'anak',
 'beli',
 'sekali',
 'mohon',
 'sampai',
 'makanan',
 'mahal',
 'sering',
 'setiap',
 'grab',
 'masih',
 'pas',
 'baik',
 'jangan',
 'klo',
 'saja',
 'drivernya',
 '1',
 'update',
 'kali',
 'sy',
 'membantu',
 'perbaiki',
 'dap

In [ ]:
w2v.vectors

array([[ 0.42206162,  0.39641923, -0.3353783 , ...,  1.7002219 ,
        -0.29721534,  0.3390539 ],
       [ 0.6896863 , -0.49652457, -0.20799543, ...,  1.2714648 ,
         0.31896228,  0.18447943],
       [ 1.8878876 , -0.26006195, -0.2489014 , ...,  0.16955864,
        -1.5304234 ,  0.62045586],
       ...,
       [-0.22221294,  2.7898748 , -1.1529365 , ..., -1.1192856 ,
         5.830262  , -2.414958  ],
       [-1.9221032 , -0.30869097, -0.15714695, ...,  1.0166074 ,
         0.22371383, -0.82765543],
       [-2.1638658 ,  0.27046654, -2.9639292 , ..., -2.0618758 ,
         3.7019897 , -0.49304986]], dtype=float32)

In [ ]:
w2v.vector_size

128

VECKTOR PER KATA

In [ ]:
w2v["ojek"]

array([-2.7281451 , -6.000401  ,  5.44974   , -5.2654095 ,  2.6252422 ,
       -0.5337025 ,  3.4217653 , -2.2142172 , -3.340556  ,  0.56790215,
        0.17058674,  2.1877904 ,  3.5497987 ,  0.6304604 ,  2.2526524 ,
       -1.6134484 ,  4.95471   , -1.2928525 ,  1.5844272 ,  1.9939011 ,
        2.3745198 , -1.3574089 ,  5.5838504 ,  0.8968459 ,  0.4184939 ,
       -1.7728797 , -4.931815  ,  3.9175138 ,  2.8555667 ,  0.9790607 ,
       -3.087227  , -0.44805232,  0.3780997 , -1.2169986 ,  0.04416767,
       -1.6029932 ,  0.03226498, -0.43664566,  0.49338084, -0.3915332 ,
       -1.5345854 , -0.5894165 ,  0.9515085 , -1.4721835 , -2.6181421 ,
        5.127873  , -2.0745056 ,  5.9724455 ,  2.7021158 , -5.324708  ,
        1.338573  ,  2.27107   ,  1.2752246 , -4.1307683 ,  1.7599427 ,
       -2.7823696 , -3.2415514 , -0.49133593,  2.3861742 , -0.31527832,
        2.29073   , -3.0810342 ,  1.2386961 ,  1.2602637 ,  1.23086   ,
       -1.4484092 , -0.864277  ,  0.05379932, -0.00969137,  2.24

In [ ]:
w2v["motor"]

array([-6.4915733e+00,  5.8320439e-01,  1.4181687e+00,  3.4081664e+00,
       -8.6047962e-02, -3.7219105e+00,  8.3192980e-01, -3.2062385e+00,
       -1.9550999e+00, -1.8502498e+00,  1.6181645e+00, -4.5442754e-01,
       -2.2085593e+00, -4.5427027e+00, -2.9049397e-01,  3.7040988e-03,
        8.0218363e+00, -5.6848741e-01, -1.6047965e+00, -8.9562148e-01,
        1.0994214e+00, -4.5246443e-01, -3.4856350e+00,  3.6534527e-01,
       -3.0056124e+00, -3.9108958e+00,  2.3616595e+00, -2.0569537e+00,
        5.8988374e-01, -4.4713120e+00, -1.0885259e+00,  3.3397007e+00,
       -5.4123192e+00,  1.7241836e+00,  2.4265411e+00, -1.4358517e+00,
       -1.9374678e+00, -1.7086697e-01, -1.3515331e+00, -6.5846014e-01,
        3.0843825e+00, -8.3288246e-01,  2.0825517e+00, -9.9643272e-01,
        2.9178369e+00, -6.8937379e-01, -4.6742535e-01,  3.0780940e+00,
        5.0679317e+00, -2.4942353e+00, -3.3524287e+00, -6.0780106e+00,
        2.6042628e-01, -3.0695958e+00,  2.3890604e-01, -6.0512319e-02,
      

In [ ]:
w2v["pas"]

array([ 1.279511  , -1.6876439 ,  1.6206095 ,  3.0482886 , -4.045567  ,
       -0.5757186 ,  2.5251799 , -0.0662902 , -1.8459748 ,  0.36296824,
        1.3424649 ,  0.2639051 ,  0.29276535,  5.0088315 ,  1.6525795 ,
        0.51579803, -2.5006044 ,  2.2201664 ,  2.0773125 , -4.0939627 ,
       -0.09414881,  1.5513971 , -2.815157  , -0.7263299 ,  2.0126834 ,
        0.39240596, -0.96005523,  4.8683248 , -0.3162005 , -1.3349618 ,
       -0.15869553,  2.7128828 ,  0.74648917,  4.0678725 ,  4.491831  ,
       -1.3120923 ,  4.1839256 , -1.178979  ,  2.1862373 , -3.5714927 ,
       -2.243511  ,  0.8946876 ,  5.398364  ,  0.2791665 , -7.7484    ,
        5.531199  ,  2.5957482 , -4.817103  , -2.1643488 , -0.28308183,
       -3.5009768 ,  2.490924  ,  1.4919512 ,  3.557849  ,  1.788169  ,
       -2.1812372 ,  3.3236847 , -4.9716496 ,  1.7792273 ,  2.2515795 ,
       -0.35440302, -2.542108  , -0.96389484,  6.869047  ,  2.9458296 ,
       -2.7244356 ,  3.8820984 , -2.5192637 , -0.07411576,  0.48

In [ ]:
w2v["bisa"]

array([-0.51383114, -0.18336022,  2.0397377 , -0.8201859 ,  0.46264133,
        0.7503604 ,  1.1599263 ,  1.9768313 ,  1.0233968 , -1.5453731 ,
        0.99644834, -0.24135207, -0.8646231 ,  0.04569877, -1.6401193 ,
        0.7293813 ,  2.3119652 , -0.7064593 ,  0.94104373,  0.04744643,
       -0.92456114, -1.1446984 , -2.3582652 ,  0.8093872 , -0.49827835,
        1.2123709 ,  0.39756075,  0.94281936, -0.94241   , -0.46417746,
        2.5897627 ,  0.11192237,  2.1148415 , -0.4099717 , -2.6824703 ,
       -0.4381886 , -2.624135  , -0.49147767, -0.16616301,  0.05135469,
       -0.94494706,  0.6341606 , -0.83433336,  0.6434729 ,  2.204108  ,
       -1.3000977 ,  1.0283047 ,  1.531418  , -0.03560249,  0.44774428,
       -0.32079512,  0.39272696,  1.387812  , -0.0098126 ,  0.07765386,
       -0.474203  , -1.282157  , -0.8648998 , -0.635255  , -2.181334  ,
        0.59576416,  1.1558952 , -1.0354066 , -1.1522707 , -2.2169573 ,
        0.789458  , -0.01103628,  1.7999854 ,  0.9982598 ,  0.50

KEMIRIPAN KATA

In [ ]:
w2v.similar_by_word ('cash',topn=10)

[('selfie', 0.3337092697620392),
 ('hrus', 0.2793281674385071),
 ('sumpah', 0.25882488489151),
 ('atm', 0.2539178133010864),
 ('tunai', 0.25230148434638977),
 ('pajangan', 0.23490026593208313),
 ('or', 0.23343676328659058),
 ('kepotong', 0.23062272369861603),
 ('berapa', 0.2242451310157776),
 ('diupgrade', 0.2241418957710266)]

In [ ]:
w2v.similar_by_word ('harga',topn=10)

[('15rb', 0.2879251539707184),
 ('tersedia', 0.286716103553772),
 ('melulu', 0.2579346299171448),
 ('10k', 0.2573654353618622),
 ('draiver', 0.24980220198631287),
 ('belanja', 0.23806363344192505),
 ('bang', 0.23291349411010742),
 ('mahal', 0.22386324405670166),
 ('ngak', 0.22077247500419617),
 ('gk', 0.21975848078727722)]

In [ ]:
w2v.similar_by_word ('mahal',topn=10)

[('naik', 0.3126436173915863),
 ('parah', 0.3008882403373718),
 ('asyik', 0.30008918046951294),
 ('gede', 0.29791855812072754),
 ('ringan', 0.26195335388183594),
 ('65rb', 0.25756508111953735),
 ('turun', 0.24178291857242584),
 ('kesini', 0.24152010679244995),
 ('rute', 0.23668906092643738),
 ('rakus', 0.2343841791152954)]

In [ ]:
w2v.similar_by_word ('murah',topn=10)

[('baik', 0.29826971888542175),
 ('ojek', 0.28697943687438965),
 ('pemakaian', 0.28474366664886475),
 ('customer', 0.2845420837402344),
 ('bermanfaat', 0.2787347137928009),
 ('ringan', 0.2760847806930542),
 ('pke', 0.2728287875652313),
 ('gofood', 0.27027156949043274),
 ('berguna', 0.26295751333236694),
 ('praktis', 0.2582087814807892)]

In [ ]:
from umap import UMAP
import numpy as np
import pandas as pd
import plotly.express as px

In [ ]:
df


umap1     umap2
0      8.095659  3.123703
1      8.698342  1.733129
2      8.196145  3.941696
3      8.021092  3.249894
4      8.920944  3.435242
...         ...       ...
1694   8.381380  2.384864
1695   8.166431  0.882493
1696   9.399871  2.755689
1697  10.073964  3.882653
1698   8.302364  2.020444

[1699 rows x 2 columns]

In [ ]:
X = UMAP().fit_transform(w2v.vectors)

In [ ]:
df = pd.DataFrame(X, columns=["umap1","umap2"])
df["text"] = w2v.index2word

In [ ]:
df

umap1     umap2     text
0     7.920763  6.454479        ,
1     8.235102  7.667765        .
2     7.627625  8.473227     saya
3     7.835123  5.383552        !
4     8.042992  7.751652       di
...        ...       ...      ...
1694  8.781703  7.901196  ngilang
1695  8.454138  9.523963  referal
1696  8.606898  5.672657  ngutang
1697  9.269079  7.747966   daging
1698  7.658562  5.464285    sayaa

[1699 rows x 3 columns]

In [ ]:
fig = px.scatter(df, x="umap1", y="umap2", text="text")
fig.update_traces(textposition='top center')
fig.update_layout(height=800, title_text='Reduce Word2Vec Vicualisation')
fig.show()

HIGH ORDER VISUALISATION